# Generated by Django 5.2.4 on 2026-01-31 14:57

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btmapp', '0002_userregisteration_city_userregisteration_door_no_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userregisteration',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AddField(
            model_name='userregisteration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 1, 31, 14, 57, 13, 764351, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userregisteration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userregisteration',
            name='door_no',
            field=models.CharField(help_text='Door/House number', max_length=20),
        ),
        migrations.AlterField(
            model_name='userregisteration',
            name='phone',
            field=models.PositiveBigIntegerField(help_text='10-digit mobile number', validators=[django.core.validators.MinValueValidator(1000000000, message='Phone number must be 10 digits'), django.core.validators.MaxValueValidator(9999999999, message='Phone number must be 10 digits')]),
        ),
        migrations.AlterField(
            model_name='userregisteration',
            name='pincode',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Pincode must be exactly 6 digits', regex='^\\d{6}$')]),
        ),
        migrations.AlterField(
            model_name='userregisteration',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userregisteration', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userregisteration',
            name='userpic',
            field=models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='profiles/%Y/%m/'),
        ),
    ]
