# Generated by Django 5.2.4 on 2026-02-03 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btmapp', '0003_alter_userregisteration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregisteration',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userregisteration',
            name='door_no',
            field=models.CharField(blank=True, help_text='Door/House number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userregisteration',
            name='landmark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userregisteration',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator(message='Pincode must be exactly 6 digits', regex='^\\d{6}$')]),
        ),
        migrations.AlterField(
            model_name='userregisteration',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userregisteration',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
