# Generated by Django 5.2.4 on 2026-03-17 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('btmapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ceo', models.CharField(max_length=50)),
                ('est_year', models.IntegerField()),
                ('origin', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos')),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btmapp.userregistration')),
            ],
            options={
                'verbose_name_plural': 'Enquiries',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('seat_capacity', models.IntegerField()),
                ('fuel_type', models.CharField(max_length=100)),
                ('cc', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('price', models.IntegerField()),
                ('prod_image', models.ImageField(blank=True, null=True, upload_to='products')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='carsapp.company')),
            ],
        ),
        migrations.CreateModel(
            name='ProductExteriorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exterior', models.ImageField(blank=True, null=True, upload_to='exterior')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exterior_images', to='carsapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInteriorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interior', models.ImageField(blank=True, null=True, upload_to='interior')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interior_images', to='carsapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='TestDriveBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('time_slot', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_drive_bookings', to='carsapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btmapp.userregistration')),
            ],
            options={
                'verbose_name': 'Test Drive Booking',
                'verbose_name_plural': 'Test Drive Bookings',
            },
        ),
    ]
