# Generated by Django 5.2.4 on 2025-09-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsapp', '0002_products_cc_products_color_products_fuel_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='prod_image',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
    ]
