# Generated by Django 5.2.4 on 2025-09-16 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btmapp', '0002_userregisteration_city_userregisteration_door_no_and_more'),
        ('carsapp', '0004_productexteriorimgs_productinteriorimgs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Test_Drive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('t_date', models.DateField()),
                ('time_slot', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_drives', to='carsapp.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_drives', to='btmapp.userregisteration')),
            ],
        ),
    ]
