# Generated by Django 5.2.4 on 2025-09-16 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btmapp', '0002_userregisteration_city_userregisteration_door_no_and_more'),
        ('carsapp', '0005_book_test_drive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_test_drive',
            name='email',
        ),
        migrations.RemoveField(
            model_name='book_test_drive',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='book_test_drive',
            name='product',
        ),
        migrations.AddField(
            model_name='book_test_drive',
            name='product_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='booked_test_drives', to='carsapp.products'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book_test_drive',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btmapp.userregisteration'),
        ),
    ]
