# Generated by Django 5.2.4 on 2025-09-19 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentalCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('CNG', 'CNG'), ('EV', 'EV')], max_length=20)),
                ('seat_capacity', models.IntegerField(choices=[(5, '5 Seater'), (7, '7 Seater')])),
                ('transmission_type', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=20)),
                ('total_km_driven', models.PositiveIntegerField()),
                ('amenities', models.TextField()),
                ('bootspace', models.CharField(max_length=50)),
                ('rating', models.CharField(choices=[('3/5', '3/5'), ('4/5', '4/5'), ('5/5', '5/5')], max_length=10)),
                ('car_img', models.ImageField(upload_to='carimg/')),
            ],
        ),
    ]
