# Generated by Django 5.2.4 on 2025-09-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalcars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalcar',
            name='milage',
            field=models.FloatField(default=15, help_text='Mileage (km per litre)'),
        ),
    ]
