# Generated by Django 5.2.4 on 2025-09-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalcars', '0002_rentalcar_milage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalcar',
            name='milage',
            field=models.FloatField(help_text='Mileage (km per litre)'),
        ),
    ]
